export const SET_GOOD_MUTATION = 'SET_GOOD_MUTATION';
export const SET_ORDERGOOD_MUTATION = 'SET_ORDERGOOD_MUTATION';
export const SET_ADDRESSLIST_MUTATION = 'SET_ADDRESSLIST_MUTATION';
export const SET_EDITADDRESS_MUTATION = 'SET_EDITADDRESS_MUTATION';
export const SET_ADDRESSID_MUTATION = 'SET_ADDRESSID_MUTATION';
